from sqlalchemy import Column, String, DateTime, Text, Integer, Float, Boolean, Index
from app.database import Base
from sqlalchemy.orm import relationship
import datetime

class Customer(Base):
    __tablename__ = "customers"
    
    id = Column(Integer, primary_key=True, index=True)
    instance_id = Column(String(100), unique=True, index=True, nullable=False)
    
    # Customer Details table fields
    customer_name = Column(String(500), nullable=True)  # Increased size
    phone_number = Column(String(50), nullable=True)
    email = Column(String(500), nullable=True)  # Increased size
    pan_number = Column(String(50), nullable=True)
    location = Column(String(1000), nullable=True)  # Increased size
    branch_id = Column(String(100), nullable=True)
    
    last_updated_by = Column(String(100), nullable=True) 

    followups = relationship("FollowUp", back_populates="customer", cascade="all, delete-orphan")
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)


class AMCAgreement(Base):
    __tablename__ = "amc_agreements"
    
    id = Column(Integer, primary_key=True, index=True)
    instance_id = Column(String(100), index=True, nullable=True)
    
    # All columns with increased sizes
    zone_name = Column(String(200), nullable=True)
    sd_id = Column(String(100), nullable=True)
    sd_name = Column(String(500), nullable=True)
    branch_id = Column(String(100), nullable=True)
    branch_name = Column(String(500), nullable=True)
    segment = Column(String(200), nullable=True)
    kva_rating = Column(String(100), nullable=True)
    engine_model = Column(String(200), nullable=True)
    agreement_number = Column(String(200), nullable=True, index=True)
    number_of_agreement_years = Column(Integer, nullable=True)
    agreement_name = Column(String(500), nullable=True)
    agreement_status = Column(String(100), nullable=True)
    agreement_type = Column(String(100), nullable=True)
    agreement_created_date = Column(DateTime, nullable=True)
    agreement_start_date = Column(DateTime, nullable=True)
    agreement_end_date = Column(DateTime, nullable=True)
    agreement_product_name = Column(String(500), nullable=True)
    last_agreement_number = Column(String(200), nullable=True)
    last_agreement_no_of_years = Column(Integer, nullable=True)
    last_agreement_type = Column(String(100), nullable=True)
    last_agreement_status = Column(String(100), nullable=True)
    last_agreement_product_name = Column(String(500), nullable=True)
    last_agreement_start_date = Column(DateTime, nullable=True)
    last_agreement_end_date = Column(DateTime, nullable=True)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)


class AssetDetailed(Base):
    __tablename__ = "asset_detailed"
    
    id = Column(Integer, primary_key=True, index=True)
    instance_id = Column(String(100), index=True, nullable=True)
    
    # All columns with increased sizes
    zone_name = Column(String(200), nullable=True)
    sd_id = Column(String(100), nullable=True)
    sd_name = Column(String(500), nullable=True)
    branch_id = Column(String(100), nullable=True)
    branch_name = Column(String(500), nullable=True)
    district = Column(String(200), nullable=True)
    asset_number = Column(String(200), nullable=True, index=True)
    commissioning_date = Column(DateTime, nullable=True)
    installation_date = Column(DateTime, nullable=True)
    goem_oem = Column(String(200), nullable=True)
    application_code = Column(String(200), nullable=True)
    engine_serial_no = Column(String(200), nullable=True, index=True)
    engine_model = Column(String(200), nullable=True)
    account_name = Column(String(500), nullable=True)
    customer_name = Column(String(500), nullable=True)
    contact_phone_number = Column(String(50), nullable=True)
    contact_email_id = Column(String(500), nullable=True)
    warranty_expiry_date = Column(DateTime, nullable=True)
    installation_site_address = Column(Text, nullable=True)  # Using Text for long addresses
    product_segment = Column(String(200), nullable=True)
    segment = Column(String(200), nullable=True)
    customer_segment = Column(String(200), nullable=True)
    asset_operational_status = Column(String(200), nullable=True)
    krm_number = Column(String(200), nullable=True, index=True)
    krm_status = Column(String(100), nullable=True)
    krm_active_date = Column(DateTime, nullable=True)
    krm_inactive_date = Column(DateTime, nullable=True)
    krm_subscription_start_date = Column(DateTime, nullable=True)
    krm_subscription_end_date = Column(DateTime, nullable=True)
    kva_rating = Column(String(100), nullable=True)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)


class AssetService(Base):
    __tablename__ = "oil_services"
    
    id = Column(Integer, primary_key=True, index=True)
    instance_id = Column(String(100), index=True, nullable=True)
    
    # All columns with increased sizes
    zone_name = Column(String(200), nullable=True)
    sd_id = Column(String(100), nullable=True)
    sd_name = Column(String(500), nullable=True)
    branch_id = Column(String(100), nullable=True)
    branch_name = Column(String(500), nullable=True)
    asset_number = Column(String(200), nullable=True, index=True)
    commissioning_date = Column(DateTime, nullable=True)
    product_segment = Column(String(200), nullable=True)
    application_code = Column(String(200), nullable=True)
    engine_serial_no = Column(String(200), nullable=True, index=True)
    account_name = Column(String(500), nullable=True)
    contact_phone_number = Column(String(50), nullable=True)
    last_closed_sr_number = Column(String(200), nullable=True)
    last_sr_type = Column(String(200), nullable=True)
    last_sr_subtype = Column(String(200), nullable=True)
    last_sr_close_date = Column(DateTime, nullable=True)
    last_oil_change_sr_number = Column(String(200), nullable=True)
    last_oil_change_sr_type = Column(String(200), nullable=True)
    last_oil_change_sr_sub_type = Column(String(200), nullable=True)
    last_oil_change_date = Column(DateTime, nullable=True)
    installation_site_address = Column(Text, nullable=True)
    last_service_hrs = Column(String(100), nullable=True)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)


class AnubandhanPlusQuote(Base):
    __tablename__ = "anubandhan_plus_quotes"
    
    id = Column(Integer, primary_key=True, index=True)
    instance_id = Column(String(100), index=True, nullable=True)
    branch_id = Column(String(100), nullable=True)
    
    # All columns with increased sizes
    id_col = Column(String(100), nullable=True)
    quotation_ref_no = Column(String(200), nullable=True, index=True)
    company_name = Column(String(500), nullable=True)
    engine_no = Column(String(200), nullable=True, index=True)
    contact_person_name = Column(String(500), nullable=True)
    mobile_no = Column(String(50), nullable=True)
    email_id = Column(String(500), nullable=True)
    genset_kva = Column(String(100), nullable=True)
    zone = Column(String(200), nullable=True)
    state = Column(String(200), nullable=True)
    city = Column(String(200), nullable=True)
    location = Column(String(500), nullable=True)
    no_of_years = Column(Integer, nullable=True)
    genset_running_per_year = Column(String(100), nullable=True)
    created_date_time = Column(DateTime, nullable=True)
    status = Column(String(100), nullable=True)
    payment_type = Column(String(100), nullable=True)
    transaction_id = Column(String(200), nullable=True)
    bank_name = Column(String(500), nullable=True)
    account_no = Column(String(200), nullable=True)
    date_of_payment = Column(DateTime, nullable=True)
    payment_update_date_time = Column(DateTime, nullable=True)
    is_neft_confirm = Column(Boolean, default=False)
    is_cheque_confirm = Column(Boolean, default=False)
    cheque_deposited_address = Column(Text, nullable=True)
    cheque_given_dealership = Column(String(500), nullable=True)
    cheque_deposited = Column(String(200), nullable=True)
    cheque_to_dealer = Column(String(200), nullable=True)
    employee_name = Column(String(500), nullable=True)
    pulse_id = Column(String(200), nullable=True)
    is_invoice_sent = Column(Boolean, default=False)
    is_refund = Column(Boolean, default=False)
    agent_id = Column(String(200), nullable=True)
    quote_price = Column(Float, nullable=True)
    quotation_value_including_tax = Column(Float, nullable=True)
    name_of_agent = Column(String(500), nullable=True)
    actual_amount = Column(Float, nullable=True)
    reason_of_short_payment = Column(Text, nullable=True)
    status_updated_by_admin = Column(Text, nullable=True)  # Changed to Text for long messages
    quotation_expiry_date = Column(DateTime, nullable=True)
    is_expired = Column(Boolean, default=False)
    payment_updated_month = Column(String(50), nullable=True)
    pulse_instance_id = Column(String(200), nullable=True)
    new_price_applicable = Column(Boolean, default=False)
    quotation_type = Column(String(50), nullable=True)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)


class AnubandhanQuote(Base):
    __tablename__ = "anubandhan_quotes"
    
    id = Column(Integer, primary_key=True, index=True)
    instance_id = Column(String(100), index=True, nullable=True)
    branch_id = Column(String(100), nullable=True)
    
    # Same as AnubandhanPlusQuote but without quotation_type
    id_col = Column(String(100), nullable=True)
    quotation_ref_no = Column(String(200), nullable=True, index=True)
    company_name = Column(String(500), nullable=True)
    engine_no = Column(String(200), nullable=True, index=True)
    contact_person_name = Column(String(500), nullable=True)
    mobile_no = Column(String(50), nullable=True)
    email_id = Column(String(500), nullable=True)
    genset_kva = Column(String(100), nullable=True)
    zone = Column(String(200), nullable=True)
    state = Column(String(200), nullable=True)
    city = Column(String(200), nullable=True)
    location = Column(String(500), nullable=True)
    no_of_years = Column(Integer, nullable=True)
    genset_running_per_year = Column(String(100), nullable=True)
    created_date_time = Column(DateTime, nullable=True)
    status = Column(String(100), nullable=True)
    payment_type = Column(String(100), nullable=True)
    transaction_id = Column(String(200), nullable=True)
    bank_name = Column(String(500), nullable=True)
    account_no = Column(String(200), nullable=True)
    date_of_payment = Column(DateTime, nullable=True)
    payment_update_date_time = Column(DateTime, nullable=True)
    is_neft_confirm = Column(Boolean, default=False)
    is_cheque_confirm = Column(Boolean, default=False)
    cheque_deposited_address = Column(Text, nullable=True)
    cheque_given_dealership = Column(String(500), nullable=True)
    cheque_deposited = Column(String(200), nullable=True)
    cheque_to_dealer = Column(String(200), nullable=True)
    employee_name = Column(String(500), nullable=True)
    pulse_id = Column(String(200), nullable=True)
    is_invoice_sent = Column(Boolean, default=False)
    is_refund = Column(Boolean, default=False)
    agent_id = Column(String(200), nullable=True)
    quote_price = Column(Float, nullable=True)
    quotation_value_including_tax = Column(Float, nullable=True)
    name_of_agent = Column(String(500), nullable=True)
    actual_amount = Column(Float, nullable=True)
    reason_of_short_payment = Column(Text, nullable=True)
    status_updated_by_admin = Column(Text, nullable=True)  # Changed to Text
    quotation_expiry_date = Column(DateTime, nullable=True)
    is_expired = Column(Boolean, default=False)
    payment_updated_month = Column(String(50), nullable=True)
    pulse_instance_id = Column(String(200), nullable=True)
    new_price_applicable = Column(Boolean, default=False)
    quotation_type = Column(String(50), nullable=True)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)


class BandhanPlusQuote(Base):
    __tablename__ = "bandhan_plus_quotes"
    
    id = Column(Integer, primary_key=True, index=True)
    instance_id = Column(String(100), index=True, nullable=True)
    branch_id = Column(String(100), nullable=True)
    
    # Same structure as AnubandhanPlusQuote
    id_col = Column(String(100), nullable=True)
    quotation_ref_no = Column(String(200), nullable=True, index=True)
    company_name = Column(String(500), nullable=True)
    engine_no = Column(String(200), nullable=True, index=True)
    contact_person_name = Column(String(500), nullable=True)
    mobile_no = Column(String(50), nullable=True)
    email_id = Column(String(500), nullable=True)
    genset_kva = Column(String(100), nullable=True)
    zone = Column(String(200), nullable=True)
    state = Column(String(200), nullable=True)
    city = Column(String(200), nullable=True)
    location = Column(String(500), nullable=True)
    no_of_years = Column(Integer, nullable=True)
    genset_running_per_year = Column(String(100), nullable=True)
    created_date_time = Column(DateTime, nullable=True)
    status = Column(String(100), nullable=True)
    payment_type = Column(String(100), nullable=True)
    transaction_id = Column(String(200), nullable=True)
    bank_name = Column(String(500), nullable=True)
    account_no = Column(String(200), nullable=True)
    date_of_payment = Column(DateTime, nullable=True)
    payment_update_date_time = Column(DateTime, nullable=True)
    is_neft_confirm = Column(Boolean, default=False)
    is_cheque_confirm = Column(Boolean, default=False)
    cheque_deposited_address = Column(Text, nullable=True)
    cheque_given_dealership = Column(String(500), nullable=True)
    cheque_deposited = Column(String(200), nullable=True)
    cheque_to_dealer = Column(String(200), nullable=True)
    employee_name = Column(String(500), nullable=True)
    pulse_id = Column(String(200), nullable=True)
    is_invoice_sent = Column(Boolean, default=False)
    is_refund = Column(Boolean, default=False)
    agent_id = Column(String(200), nullable=True)
    quote_price = Column(Float, nullable=True)
    quotation_value_including_tax = Column(Float, nullable=True)
    name_of_agent = Column(String(500), nullable=True)
    actual_amount = Column(Float, nullable=True)
    reason_of_short_payment = Column(Text, nullable=True)
    status_updated_by_admin = Column(Text, nullable=True)  # Changed to Text
    quotation_expiry_date = Column(DateTime, nullable=True)
    is_expired = Column(Boolean, default=False)
    payment_updated_month = Column(String(50), nullable=True)
    pulse_instance_id = Column(String(200), nullable=True)
    new_price_applicable = Column(Boolean, default=False)
    quotation_type = Column(String(50), nullable=True)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)


class PulseQuotation(Base):
    __tablename__ = "pulse_quotations"
    
    id = Column(Integer, primary_key=True, index=True)
    instance_id = Column(String(100), index=True, nullable=True)
    branch_id = Column(String(100), nullable=True)
    
    # All columns with increased sizes
    creation_date = Column(DateTime, nullable=True)
    quote_id = Column(String(200), nullable=True, index=True)
    first_level_observations = Column(Text, nullable=True)
    quote_status = Column(String(100), nullable=True)
    sr_type = Column(String(200), nullable=True)
    sr_sub_type = Column(String(200), nullable=True)
    instance_id_col = Column(String(200), nullable=True)
    account = Column(String(500), nullable=True)
    bill_to_address = Column(Text, nullable=True)
    ship_to_address = Column(Text, nullable=True)
    first_name = Column(String(200), nullable=True)
    last_name = Column(String(200), nullable=True)
    contact_phone_number = Column(String(50), nullable=True)
    installation_site_address = Column(Text, nullable=True)
    contact_primary_email = Column(String(500), nullable=True)
    service_dealer = Column(String(500), nullable=True)
    labor_amount = Column(Float, nullable=True)
    parts_amount = Column(Float, nullable=True)
    total_amount = Column(Float, nullable=True)
    prepared_by = Column(String(500), nullable=True)
    recommended_by = Column(String(500), nullable=True)
    finance_company_address = Column(Text, nullable=True)
    account_number = Column(String(200), nullable=True)
    purpose_of_quotation = Column(Text, nullable=True)
    sr_number = Column(String(200), nullable=True)
    quote_revised_flag = Column(Boolean, default=False)
    quote_submitted_date = Column(DateTime, nullable=True)
    exception_enquiry_no = Column(String(200), nullable=True)
    lead_no = Column(String(200), nullable=True)
    quotation_lead_assigned_name = Column(String(500), nullable=True)
    quotation_lead_assigned_job_title = Column(String(500), nullable=True)
    quotation_lead_assigned_phone = Column(String(50), nullable=True)
    quotation_lead_assigned_uid = Column(String(200), nullable=True)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)


class RegularBandhan(Base):
    __tablename__ = "regular_bandhan"
    
    id = Column(Integer, primary_key=True, index=True)
    instance_id = Column(String(100), index=True, nullable=True)
    branch_id = Column(String(100), nullable=True)
    
    # All columns with increased sizes - Text for long fields
    name_of_agent = Column(String(500), nullable=True)
    quotation_ref_no = Column(String(200), nullable=True, index=True)
    password = Column(String(200), nullable=True)
    genset_number = Column(String(200), nullable=True, index=True)
    name = Column(String(500), nullable=True)
    email = Column(String(500), nullable=True)
    mobile = Column(String(50), nullable=True)
    pan_card_no = Column(String(50), nullable=True)
    billing_state = Column(String(200), nullable=True)
    billing_city = Column(String(200), nullable=True)
    billing_location = Column(String(500), nullable=True)
    billing_address_1 = Column(Text, nullable=True)
    billing_address_2 = Column(Text, nullable=True)
    billing_pincode = Column(String(20), nullable=True)
    dg_state = Column(String(200), nullable=True)
    dg_city = Column(String(200), nullable=True)
    dg_location = Column(String(500), nullable=True)
    dg_address_1 = Column(Text, nullable=True)
    dg_address_2 = Column(Text, nullable=True)
    dg_pincode = Column(String(20), nullable=True)
    type_of_customer = Column(String(200), nullable=True)
    date = Column(DateTime, nullable=True)
    gstn_no = Column(String(100), nullable=True)
    payment_type = Column(String(100), nullable=True)
    payment_update_date = Column(DateTime, nullable=True)
    contact_person_name = Column(String(500), nullable=True)
    zone = Column(String(200), nullable=True)
    actual_amount = Column(Float, nullable=True)
    reason_of_short_payment = Column(Text, nullable=True)
    status_updated_by_admin = Column(Text, nullable=True)  # Changed to Text for long messages
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)


class LMSData(Base):
    __tablename__ = "lms_data"
    
    id = Column(Integer, primary_key=True, index=True)
    instance_id = Column(String(100), index=True, nullable=True)
    
    # ---- Existing columns (kept) ----
    lead_number = Column(String(200), nullable=True, index=True)
    lead_created_date = Column(DateTime, nullable=True)
    mode_of_lead_creation = Column(String(200), nullable=True)
    lead_raised_by = Column(String(500), nullable=True)
    lead_raised_for = Column(String(500), nullable=True)
    sd_name = Column(String(500), nullable=True)
    sd_id = Column(String(100), nullable=True)
    branch_name = Column(String(500), nullable=True)
    branch_id = Column(String(100), nullable=True)
    product_list = Column(String(500), nullable=True)
    product_type = Column(String(200), nullable=True)
    lead_assigned_to = Column(String(500), nullable=True)
    lead_status = Column(String(200), nullable=True)
    account_id = Column(String(200), nullable=True)
    account_name = Column(String(500), nullable=True)
    zone = Column(String(200), nullable=True)
    lead_sr_number = Column(String(200), nullable=True)
    instance_id_col = Column(String(200), nullable=True)
    engine_model = Column(String(200), nullable=True)
    kva_rating = Column(String(100), nullable=True)
    service_engineer_name = Column(String(500), nullable=True)
    tele_caller_name = Column(String(500), nullable=True)
    quotation_number = Column(String(200), nullable=True)
    quotation_submit_date = Column(DateTime, nullable=True)
    quotation_approval_date = Column(DateTime, nullable=True)
    order_number = Column(String(200), nullable=True)
    order_creation_date = Column(DateTime, nullable=True)
    
    # ---- NEW columns for the new LMS file format ----
    sr_type = Column(String(200), nullable=True)
    sr_sub_type = Column(String(200), nullable=True)
    sr_sub_type_2 = Column(String(200), nullable=True)          # second "SR Sub Type" column in file
    account_contact_number = Column(String(50), nullable=True)
    account_contact_email_id = Column(String(500), nullable=True)
    tele_caller_uid = Column(String(100), nullable=True)
    tele_caller_mobile_number = Column(String(50), nullable=True)
    enquiry_allocation_remarks = Column(Text, nullable=True)
    engine_app_code = Column(String(200), nullable=True)
    engine_serial_no = Column(String(200), nullable=True, index=True)
    pin_code = Column(String(20), nullable=True)
    segment = Column(String(200), nullable=True)
    commissioning_date = Column(DateTime, nullable=True)
    installation_site_address = Column(Text, nullable=True)
    city = Column(String(200), nullable=True)
    district = Column(String(200), nullable=True)
    state = Column(String(200), nullable=True)
    asset_contact_name = Column(String(500), nullable=True)
    asset_contact_phone_number = Column(String(50), nullable=True)
    efsr_contact_name = Column(String(500), nullable=True)
    efsr_customer_number = Column(String(100), nullable=True)
    qualifying_date = Column(DateTime, nullable=True)
    quotation_type = Column(String(200), nullable=True)
    quotation_labour_amt = Column(Float, nullable=True)
    quotation_part_amt = Column(Float, nullable=True)
    total_quote_amount = Column(Float, nullable=True)
    quotation_lead_assigned_name = Column(String(500), nullable=True)
    quotation_lead_assigned_uid = Column(String(100), nullable=True)
    quotation_lead_assigned_job_title = Column(String(500), nullable=True)
    enquiry_loss_reason = Column(Text, nullable=True)
    service_engineer_uid = Column(String(100), nullable=True)
    service_engineer_mobile_number = Column(String(50), nullable=True)
    sic_code = Column(String(200), nullable=True)
    sic_code_type = Column(String(200), nullable=True)
    labour_invoice_number = Column(String(200), nullable=True)
    part_invoice_amount = Column(Float, nullable=True)
    part_invoice_number = Column(String(200), nullable=True)
    lead_source = Column(String(200), nullable=True)
    next_action_required = Column(String(500), nullable=True)
    new_contact = Column(String(500), nullable=True)
    lead_contact_number = Column(String(50), nullable=True)
    next_action_date = Column(DateTime, nullable=True)
    lead_assign_to_sd = Column(String(500), nullable=True)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)


class OpenSRLoadReport(Base):
    __tablename__ = "open_sr_load_reports"
    
    id = Column(Integer, primary_key=True, index=True)
    instance_id = Column(String(100), index=True, nullable=True)
    branch_id = Column(String(100), nullable=True)  
    
    # All columns from Open SR Load Report
    service_request_no = Column(String(200), nullable=True, index=True)
    sr_due_date = Column(DateTime, nullable=True)
    appointment_date = Column(DateTime, nullable=True)
    service_dealer = Column(String(500), nullable=True)
    status = Column(String(100), nullable=True)
    sr_type = Column(String(200), nullable=True)
    sr_sub_type = Column(String(200), nullable=True)
    problem_code = Column(String(200), nullable=True)
    installation_site_address = Column(Text, nullable=True)
    engine_app_code = Column(String(200), nullable=True)
    voc = Column(String(200), nullable=True)
    engine_serial_no = Column(String(200), nullable=True, index=True)
    engine_series = Column(String(200), nullable=True)
    engine_model = Column(String(200), nullable=True)
    ticket_no = Column(String(200), nullable=True)
    segment = Column(String(200), nullable=True)
    task_start_date = Column(DateTime, nullable=True)
    task_end_date = Column(DateTime, nullable=True)
    account = Column(String(500), nullable=True)
    under_monitoring_date = Column(DateTime, nullable=True)
    under_monitoring_remark = Column(Text, nullable=True)
    convert_pm_to_wet_pm_flag = Column(String(100), nullable=True)
    efsr_engineer_remarks = Column(Text, nullable=True)
    quick_ticket_sr_comments = Column(Text, nullable=True)
    actual_sr_due_date = Column(DateTime, nullable=True)
    convert_pm_to_wet_pm_flag_updated_date = Column(DateTime, nullable=True)
    convert_pm_to_wet_pm_flag_updated_by = Column(String(500), nullable=True)
    customer_name = Column(String(500), nullable=True)
    contact_last_name = Column(String(200), nullable=True)
    customer_mobile_no = Column(String(50), nullable=True)
    genset_appcode = Column(String(200), nullable=True)
    contact_name = Column(String(500), nullable=True)
    primary_phone_no = Column(String(50), nullable=True)
    mode = Column(String(100), nullable=True)
    close_date_time = Column(DateTime, nullable=True)
    special_tool = Column(String(500), nullable=True)
    special_tool_name = Column(String(500), nullable=True)
    repeat = Column(String(100), nullable=True)
    assigned_to = Column(String(500), nullable=True)
    oil_change_flg = Column(String(100), nullable=True)
    claim_created = Column(String(100), nullable=True)
    agreement_no = Column(String(200), nullable=True)
    cancellation_reason = Column(Text, nullable=True)
    csp_cancellation_reasons = Column(String(500), nullable=True)
    csp_cancellation_remarks = Column(Text, nullable=True)
    asm_ase_remarks = Column(Text, nullable=True)
    asm_ase_remarks_date = Column(DateTime, nullable=True)
    battery_charger_availability = Column(String(100), nullable=True)
    wet_pm_due_flag = Column(String(100), nullable=True)
    cap_limit_approval_remarks = Column(Text, nullable=True)
    cap_limit_deviation_remarks = Column(Text, nullable=True)
    cap_limit_deviation_status = Column(String(100), nullable=True)
    cap_limit_user_details = Column(String(500), nullable=True)
    csp_prepone_flag = Column(String(100), nullable=True)
    csp_prepone_flag_updated_by = Column(String(500), nullable=True)
    bandhan_pm_sr_closure_within_15_days_flag = Column(String(100), nullable=True)
    bandhan_pm_lock_removal_flag_updated_by = Column(String(500), nullable=True)
    bandhan_pm_lock_removal_flag_updated_date = Column(DateTime, nullable=True)
    bandhan_pm_sr_closure_90_days_max_after_pm_due_date_flag = Column(String(100), nullable=True)
    bandhan_pm_due_date_lock_removal_flag_updated_by = Column(String(500), nullable=True)
    bandhan_pm_due_date_lock_removal_flag_updated_date = Column(DateTime, nullable=True)
    bandhan_job_card_creation_prior_to_60_days_flag = Column(String(100), nullable=True)
    bandhan_pm_jc_creation_lock_removal_flag_updated_by = Column(String(500), nullable=True)
    bandhan_pm_jc_creation_lock_removal_flag_updated_date = Column(DateTime, nullable=True)
    account_id = Column(String(200), nullable=True)
    sr_created_by = Column(String(500), nullable=True)
    efsr_krm_number = Column(String(200), nullable=True)
    dry_csp_approved_by = Column(String(500), nullable=True)
    dry_csp_approved_date = Column(DateTime, nullable=True)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)